### PR TITLE
fix(53figures): Uses sa4ss::add_figure

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
Used regex to change all html inclusion of figures to use `sa4ss::add_figure()`. Also adds full stops to the end of alternative text, changes all percent signs to be the word percent, and uses LaTeX math mode for subscripts rather than using ~.

This file was not checked for compiling.

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
I probably did not need to change the way that the subscripts were written. I can change them back if you would like?

**Review by brianlangseth-NOAA — COMMENTED** [review]
@kellijohnson-NOAA Thank you for this. The transition is fine but there are at least two things I noticed that have changed. 

First, figure 1 runs over the page number when using add_figure. I haven't checked any of the other figures. This is probably how we have the dimensions set up. It wasn't an issue with the html setup. Is there an automated solution to this? I can manually adjust width to something other than 100% but I dont see why it cant automatically adjust. 

Second, instances where we used r code ('r spp') within the html text are not read the same when used in add_figure. How do I apply r variables within the captions for add_figure?

**Comment by brianlangseth-NOAA** [comment]
Do I also need to change hyphens in labels to underscores?

**Comment by brianlangseth-NOAA** [comment]
Solutions to these include:
1. Will have to adjust width to ensure no overlap of page numbers
2. Can you glue::glue("I like {spp}") or paste("I like", spp)
3. Kelli's suggestion was to not use underscores. The solution here was that for our html we had "fig:" in some of the labels. When those are removed the labels with hyphens worked.

**Pull request merged**
